name: Generate Podcast Feeds
#on means what triggers the process to start. We will trigger when someone push smth to the main branch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: Darryll2022/podcast-generator@main





        
